"""
Convert woman_sil.png / man_sil.png  →  graphics/sprite_data.asm
Sprite format: GFX7 (ANTIC mode E), 2bpp, 96×120 px, 24 bytes/row.
Pixel value 3 (%11) = symbol (white); 0 (%00) = background (black).
"""
import numpy as np
from PIL import Image
import os

SPRITE_W  = 96   # pixels  (24 bytes × 4 px/byte)
SPRITE_H  = 120  # rows
BYTES_ROW = SPRITE_W // 4   # 24

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

def load_and_convert(fname):
    path = os.path.join(SCRIPT_DIR, fname)
    img  = Image.open(path).convert("RGBA")
    img  = img.resize((SPRITE_W, SPRITE_H), Image.LANCZOS)
    alpha = np.array(img, dtype=np.uint8)[..., 3]   # shape: (120, 96)
    opaque = (alpha > 128).astype(np.uint8)           # 1 = symbol pixel

    rows = []
    for row in range(SPRITE_H):
        out = []
        for bx in range(BYTES_ROW):
            p0 = int(opaque[row, bx*4 + 0])
            p1 = int(opaque[row, bx*4 + 1])
            p2 = int(opaque[row, bx*4 + 2])
            p3 = int(opaque[row, bx*4 + 3])
            # each opaque pixel → pixel-value 3 (%11); background → 0 (%00)
            byte = (p0 * 3) << 6 | (p1 * 3) << 4 | (p2 * 3) << 2 | (p3 * 3)
            out.append(byte)
        rows.append(out)
    return rows

def fmt_rows(rows, label):
    lines = [f"{label}"]
    for i, row in enumerate(rows):
        hex_vals = ",".join(f"${b:02X}" for b in row)
        lines.append(f"  .BYTE {hex_vals}")
    return "\n".join(lines)

man_rows = load_and_convert("man_sil.png")
wom_rows = load_and_convert("woman_sil.png")

out_path = os.path.join(SCRIPT_DIR, "sprite_data.asm")
with open(out_path, "w") as f:
    f.write("; Auto-generated by gen_sprite.py — do not edit by hand\n")
    f.write(f"; Sprite size: {SPRITE_W}x{SPRITE_H} px, {BYTES_ROW} bytes/row, {SPRITE_H*BYTES_ROW} bytes each\n")
    f.write("; GFX7 2bpp: pixel value 3=symbol(white), 0=background(black)\n\n")
    f.write(fmt_rows(man_rows, "MAN_SPR"))
    f.write("\n\n")
    f.write(fmt_rows(wom_rows, "WOM_SPR"))
    f.write("\n")

print(f"Written {out_path}")
print(f"  MAN_SPR: {SPRITE_H*BYTES_ROW} bytes")
print(f"  WOM_SPR: {SPRITE_H*BYTES_ROW} bytes")
